---
# Followed homebrew official guide: https://github.com/Homebrew/brew/blob/master/docs/Installation.md
# This role ensure Homebrew and Homebrew-Cask is installed

- name: Ensure /usr/local has correct permissions.
  file:
    path: /usr/local
    group: staff
    mode: 0775
    state: directory
  sudo: yes

# Shallow clone of homebrew to /usr/local
- name: Ensure homebrew is installed
  git:
    repo: git://github.com/Homebrew/brew.git
    version: master
    dest: /usr/local/homebrew
    update: no
    accept_hostkey: yes
    depth: 1

- name: Ensure homebrew linked to /usr/local/bin
  file:
    src: /usr/local/homebrew/bin/brew
    dest: /usr/local/bin/brew
    state: link
  sudo: yes

# Homebrew Cask
- name: Ensure Homebrew Core is installed.
  homebrew_tap: "tap=homebrew/core state=present"

# Homebrew Cask
- name: Ensure Homebrew Cask tap is installed.
  homebrew_tap: "tap=caskroom/cask state=present"

# Update homebrew
- name: Ensure formulae and casks are updated
  homebrew: update_homebrew=yes
  when: homebrew.update_to_latest

# Homebrew Taps
- name: Ensure configured taps are installed.
  homebrew_tap:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ homebrew.taps }}"
  when: homebrew.taps
- name: Ensure configured taps outside Github are installed.
  homebrew_tap:
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    state: present
  with_items: "{{ homebrew.taps_out_of_github }}"
  when: homebrew.taps_out_of_github

# Homebrew Formulae
- name: Ensure configured formulae are installed.
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew.formulae }}"
  when: homebrew.formulae

# Homebrew Casks
- name: Ensure configured casks are installed.
  homebrew_cask: "name={{ item }} state=present"
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  with_items: "{{ homebrew.casks }}"
  when: homebrew.casks

## Homebrew cleanup
- name: Cleanup
  shell: brew cleanup && brew cask cleanup
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

## Ensure Homebrew is shared with in group staff
- name: Ensure Homebrew is shared with in group staff
  file:
    path: "{{ item }}"
    group: staff
    mode: u=rwX,g=rwX,o=rX
    recurse: yes
  with_items: "{{ shared_paths }}"
  sudo: yes
  when: homebrew.shared
